name: config
root: ~/.config

on_project_start: tmux resize-pane -t config:0.0 -y 70%

windows:
  - main:
      panes:
        - nvim
        - # empty terminal
        - claude --resume
      layout: main-horizontal
