name: <%= File.basename(File.expand_path(@args[0] || '.')).sub(/^\./, '') %>
root: <%= @args[0] || '.' %>

windows:
  - main:
      panes:
        - nvim
        - # empty terminal
        - ccdc
      layout: main-horizontal
