bookmarks:
  - title: 'Roblox PRs'
    url: 'https://github.rbx.com/pulls'
  - title: 'Gmail'
    url: 'https://mail.google.com/mail/u/0/#inbox'
  - title: 'ChatGPT'
    url: 'https://chatgpt.com/'
  - title: 'GitHub'
    url: 'https://github.com/trentshaines'
  - title: 'Leetcode'
    url: 'https://leetcode.com/'
