- name: Install Homebrew and autojump on macOS
  hosts: localhost
  become: no
  tasks:
    - name: Check if Homebrew is installed
      command: brew --version
      register: brew_check
      ignore_errors: yes

    - name: Install Homebrew
      shell: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      when: brew_check.rc != 0

    - name: Install autojump via Homebrew
      community.general.homebrew:
        name: autojump
        state: present
