# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

matches:
  # === Personal Info ===
  - trigger: ":fn"
    replace: "Trent"
  - trigger: ":ln"
    replace: "Haines"
  - trigger: ":name"
    replace: "Trent Haines"
  - trigger: ":mail"
    replace: "trentshaines@gmail.com"
  - trigger: ":dmail"
    replace: "trent.haines@decagon.ai"
  - trigger: ":linkedin"
    replace: "https://www.linkedin.com/in/trentshaines/"
  - trigger: ":num"
    replace: "469-929-0757"
  - trigger: ":bday"
    replace: "11/28/2001"
  - trigger: ":linkedin"
    replace: "https://www.linkedin.com/in/trentshaines/"
  - trigger: ":github"
    replace: "https://github.com/trentshaines"
  - trigger: ":website"
    replace: "https://trent-quartz-obsidian.vercel.app/"

  # === Address ===
  - trigger: ":addr"
    replace: "325 Berry St APT 109, San Francisco, CA 94158"
  - trigger: ":street"
    replace: "325 Berry St APT 109"
  - trigger: ":city"
    replace: "San Francisco"
  - trigger: ":zip"
    replace: "94158"
  - trigger: ":csz"
    replace: "San Francisco, CA 94158"

  # === Dates & Times ===
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  - trigger: ":isodate"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"

  - trigger: ":time"
    replace: "{{mytime}}"
    vars:
      - name: mytime
        type: date
        params:
          format: "%H:%M"

  - trigger: ":now"
    replace: "{{now}}"
    vars:
      - name: now
        type: date
        params:
          format: "%Y-%m-%d %H:%M"
